graph LR
  whale(Whale)-->|lives in|water(Water)
  bear(Bear)-->|is a|mammal(Mammal)
  fish(Fish)-->|lives in|water
  whale-->|is a|mammal
  cat(Cat)-->|is a|mammal
  cat-->|has|fur
  bear-->|has|fur(Fur)
  mammal-->|is a|animal(Animal)
  fish-->|is a|animal
  mammal-->|has|vertebra(Vertebra)